import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./admin/common/SideBar";
import Header from "./admin/common/Header";
import { Toaster } from "sonner";
import { MainContext } from "./context/MainContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html
    //   lang="en"
    //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    // >
    //   <body className="min-h-full">
    //     <MainContext>
    //       <Toaster />
    //       <div className="flex h-screen overflow-hidden">
    //         <aside className="shrink-0 h-screen border-r border-gray-200  overflow-hidden">
    //           <SideBar />
    //         </aside>

    //         <div className="flex flex-1 flex-col h-screen overflow-hidden">
    //           <div className="shrink-0 border-b border-gray-200 bg-white">
    //             <Header />
    //           </div>

    //           <main className="flex-1 overflow-y-auto scrollbar-hide">
    //             {children}
    //           </main>
    //         </div>
    //       </div>
    //     </MainContext>
    //   </body>
    // </html>

    <html lang="en">
      <body>
        <MainContext>
          <Toaster />
          {children}
        </MainContext>
      </body>
    </html>
  );
}
