import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./common/Header";
import Footer from "./common/Footer";
import { Toaster } from "sonner";
import { MdError } from "react-icons/md";
import { MainContext } from "./context/MainContext";
import LoginPopup from "./common/LoginPopup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "JobListener",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainContext>
          <Toaster richColors />
          <Header />
          {children}
          <LoginPopup />
          <Footer />
        </MainContext>
      </body>
    </html>
  );
}
